create database testeval owner tp;

create table Admin(
    id serial primary key,
    email varchar(100),
    mdp varchar (100)
);

create table Auteur(
    id serial primary key,
    nom varchar(100),
    prenom varchar(100)
);

create table Contenus(
    id serial primary key,
    titre varchar(100),
    description text,
    texte text,
    images text,
    idAuteur int,
    dateParution date default now(),
    etat int default 0,
    FOREIGN KEY(idAuteur) REFERENCES Auteur(id)
);

INSERT INTO public.contenus
( titre, description, texte, images, idauteur)
VALUES('ChatGPT et l''IA sont une menace pour les métiers de l''écrit, mais pas que', 
'Au-delà de la traduction, dont la pratique devra sans doute s''adapter, la société tout entière risque de perdre des plumes avec l''apparition des nouveaux outils d''intelligence artificielle.', 
'Qu''on adule le concept de l''intelligence artificielle (IA) en général et de ChatGPT en particulier, qu''on le déteste ou qu''on s''en tamponne le coquillard, à moins de vivre dans une grotte, impossible de ne pas en avoir entendu parler, difficile de ne pas avoir un avis. Si on est traducteur et/ou journaliste, on reçoit en outre régulièrement de la part d''amis bien intentionnés (ou pas) des articles annonçant la fin de nos métiers et le début de nos ennuis. Pour les traducteurs, ce n''est vraiment pas une nouveauté. Depuis l''apparition de Google Trad, puis de DeepL, la question de la menace que représenteraient l''intelligence artificielle et la traduction automatique revient régulièrement dans les conversations avec les non-traducteurs. Or, il se trouve que les logiciels d''aide à la traduction existent depuis longtemps et qu''en fonction du champ de travail du traducteur, ils s''avèrent souvent être une aide précieuse. Pour le grand public, un «traducteur» est principalement quelqu''un qui traduit des livres (romans, essais). Ça, c''est un traducteur littéraire, à qui on peut associer le traducteur de presse. Ils ont en commun de réaliser des traductions qu''on appelle «non pragmatiques», c''est-à-dire dont l''application directe est communicationnelle. Une traduction pragmatique, c''est la traduction, par exemple, d''un contrat, d''un mode d''emploi de machine, d''un bilan d''entreprise. Ça relève d''un domaine de spécialité et requiert ce que l''on appelle une phraséologie et une terminologie particulières. Traduction (haha): la formulation et le vocabulaire de ces textes-là ne sont pas les mêmes que ceux du domaine général.', 'https://www.slate.fr/sites/default/files/styles/1060x523/public/glenn-carstens-peters-1f4muko0ung-unsplash.jpg', 2);
INSERT INTO public.contenus
( titre, description, texte, images, idauteur)
VALUES('Les couvertures de livres générées par des algorithmes sont-elles le futur de l''édition?', 'Auteur de fantasy et de science-fiction à succès, Christopher Paolini ne pensait sans doute pas que son dernier livre ferait parler de lui en raison de sa couverture. Celui qui a notamment écrit la saga Eragon sortira dans quelques mois son nouveau livre, Fractal Noise, qui est partie intégrante d''une série qu''il a baptisée le Fractalverse –et dont le visuel a été généré par une intelligence artificielle.', 'Dès que la couverture a été dévoilée, les fans ont émis leurs premiers doutes. Sur Twitter, des petits malins ont rapidement fait le lien entre d''images, qui a été générée par une intelligence artificielle. Celle-ci avait bien entendu été réarrangée, bien qu''aucun nom de graphiste ou d''artiste ne figure sur la quatrième de couverture ou à l''intérieur de l''ouvrage. Un élément qui en a étonné plus d''un, l''éditeur Tor Books ayant plutôt la réputation de promouvoir le travail de celles et ceux qui composent ses univers visuels. Face aux nombreuses réactions hostiles, la maison d''édition a décidé de publier un message sur Twitter afin d''apaiser les esprits: «Durant le processus de création de cette couverture, nous avons acheté une image provenant d''une banque d''illustrations renommée. Nous ne savions pas que cette image avait été créée par une intelligence artificielle. Notre designer maison l''a utilisée pour créer notre couverture, qui a été présentée à Christopher pour validation.» Mais selon Gizmodo, il y a un hic: connue pour ses couvertures de grande qualité, Tor Books aurait dû réaliser tôt ou tard que l''image utilisée n''était pas l''œuvre d''un être humain. Les excuses publiées sur Twitter sont trop timorées, estime le site américain, qui attire l''attention sur le fait que la maison d''édition ne s''engage pas à ne plus utiliser d''illustrations générées par intelligence artificielle. En outre, la décision de conserver cette couverture (pour un livre qui ne sortira sans doute pas avant mai 2023) fait grincer des dents chez les graphistes. ', 'https://www.slate.fr/sites/default/files/styles/1060x523/public/ai-algorithm-generated.png', 3);
INSERT INTO public.contenus
( titre, description, texte, images, idauteur)
VALUES( 'Laisseriez-vous une IA choisir votre menu au restaurant?', 'Si, lorsque vous commandez à manger, vous avez envie de tout sauf de recevoir des conseils non sollicités à propos de ce qui serait le plus adapté pour vous, alors l''innovation proposée par Raydiant ne vous est absolument pas destinée. La société basée à San Francisco a en effet mis au point un système permettant aux restaurants de vous suggérer un menu qu''ils pensent adapté à vos envies ou à vos besoins.', 'Jusqu''ici, les grandes marques de fast-food et quelques restaurants proposent à la clientèle de procéder elle-même à sa commande grâce à des bornes tactiles ou à des tablettes, et les choses s''arrêtent là. Raydiant suggère aux restaurants d''intégrer à ces dispositifs une fonctionnalité permettant de scanner chaque client afin de déterminer sa taille, son âge, son genre ou son humeur. Tout (ou presque) est paramétrable: si plusieurs personnes se trouvent devant la borne au moment de la commande, le système pourra proposer des offres adaptées aux groupes. À partir de ces informations, explique Quartz, la borne vous donnera des conseils personnalisés. Selon Bobby Marhamat, le patron de Raydiant, l''objectif est d''offrir «une expérience personnalisée au consommateur, tout en aidant les restaurants à booster leurs ventes». Plus de 4.500 établissements utilisent déjà les services de l''entreprise, et pas uniquement des restaurants: certains casinos et clubs de gym s''y sont mis, ainsi que de nombreuses boutiques. Les dérives de l''utilisation des intelligences artificielles ont souvent été mises en lumières, notamment parce qu''elles ont parfois tendance à se montrer discriminantes. Mais le PDG de Raydiant affirme que tout cela a été savamment réfléchi au sein de sa société: pas de cession de données à des tiers, ni de sauvegarde d''informations à des fins ultérieures.', 'https://images.radio-canada.ca/q_auto,w_1200/v1/alimentation/articles/16x9/fast-food-maison.jpg', 1);
INSERT INTO public.contenus
( titre, description, texte, images, idauteur)
VALUES( 'Des signaux extraterrestres seront-ils bientôt découverts par une intelligence artificielle?', 'Il y a environ 540 millions d''années, diverses formes de vie ont soudainement commencé à émerger des fonds boueux des océans de la planète: c''était l''«explosion cambrienne», et ces créatures aquatiques sont nos ancêtres. Toute la vie complexe sur Terre a évolué à partir de ces créatures sous-marines. Il aurait suffi d''une très légère augmentation du niveau d''oxygène dans l''océan au-dessus d''un certain seuil pour que la vie se développe rapidement.', 'Nous recherchons scientifiquement des signaux provenant de formes de vie intelligente au-delà de la Terre. Dernièrement, nous avons développé un système d''IA et nous l''avons entraînée à rechercher dans les données des radiotélescopes des signaux qui n''ont pas pu être générés par des processus astrophysiques naturels. Elle est maintenant plus efficace que les algorithmes classiques pour détecter ce type de signaux. Les algorithmes d''IA ne «comprennent» pas. Ils ne «pensent» pas non plus. Ils excellent dans ce que l''on appelle la «reconnaissance de motifs» (des formes répétitives, comme un motif à pois ou à rayures) et se sont révélés extrêmement utiles pour des tâches telles que la classification, mais ils ne peuvent pas résoudre de problèmes. Ils ne font que les tâches spécifiques pour lesquelles ils ont été entraînés. Ainsi, bien que l''idée d''une IA détectant une intelligence extraterrestre ressemble à l''intrigue d''un roman de science-fiction passionnant, ces deux termes sont erronés: les systèmes d''IA ne sont pas intelligents, et les recherches d''intelligences extraterrestres ne peuvent pas trouver de preuves directes d''intelligence.', 'https://www.slate.fr/sites/default/files/file-20230130-217-ye6duz.jpg', 1);
INSERT INTO public.contenus
( titre, description, texte, images, idauteur)
VALUES( 'ChatGPT va bientôt révolutionner le monde de l''économie', 'Qu''elle soit basée sur des croyances hallucinatoires ou non, une ruée vers l''or de l''intelligence artificielle a commencé au cours des derniers mois pour exploiter les opportunités commerciales attendues des modèles d''IA génératifs comme ChatGPT. Les développeurs d''applications, les startups soutenues par des entreprises et certaines des plus grandes entreprises du monde se démènent tous pour donner un sens au sensationnel bot générateur de texte publié par OpenAI en novembre dernier.', 'Vous pouvez pratiquement entendre les cris des bureaux du coin du monde entier : « Qu''est-ce que notre jeu ChatGPT ? Comment pouvons-nous gagner de l''argent avec cela? Mais alors que les entreprises et les dirigeants voient une chance claire de tirer profit, l''impact probable de la technologie sur les travailleurs et l''économie dans son ensemble est beaucoup moins évident. Malgré leurs limites, dont la principale est leur propension à inventer des choses, ChatGPT et d''autres modèles d''IA générative récemment publiés promettent d''automatiser toutes sortes de tâches qui étaient auparavant considérées comme relevant uniquement du domaine de la créativité et du raisonnement humains, de l''écriture à la création de graphiques pour résumer et analyser les données. Cela a laissé les économistes incertains de la manière dont les emplois et la productivité globale pourraient être affectés. Malgré toutes les avancées étonnantes de l''IA et d''autres outils numériques au cours de la dernière décennie, leur bilan en matière d''amélioration de la prospérité et de stimulation de la croissance économique généralisée est décourageant. Bien que quelques investisseurs et entrepreneurs soient devenus très riches, la plupart des gens n''en ont pas profité. Certains ont même été automatisés hors de leurs emplois. ChatGPT, avec ses capacités d''écriture humaines, et l''autre version récente d''OpenAI, DALL-E 2, qui génère des images à la demande, utilisent de grands modèles de langage formés sur d''énormes quantités de données. Il en va de même pour des rivaux comme Claude d''Anthropic et Bard de Google. Ces modèles dits fondamentaux, tels que GPT-3.5 d''OpenAI, sur lequel ChatGPT est basé, ou le modèle de langage concurrent de Google, LaMDA, qui alimente Bard, ont évolué rapidement ces dernières années.', 'https://static.lematin.ma/files/lematin/images/articles/2023/03/00959b4fb6ba5bad0ba7e7187a2a0fc5.jpg', 2);
INSERT INTO public.contenus
( titre, description, texte, images, idauteur)
VALUES( 'On pourra bientôt parler aux morts sur internet', 'Sera-t-il possible dans le futur de parler à l''avatar d''un de vos proches décédés? Même s''il s''agit déjà d''un scénario d''un épisode de Black Mirror, certains souhaitent en faire une possibilité réelle. Dans un tweet, cité par le New York Post, Pratik Desai, informaticien de la Silicon Valley qui travaille notamment sur l''intelligence artificielle, appelle les internautes à enregistrer régulièrement leurs parents et amis dans cette perspective.', '«Avec suffisamment de données qui peuvent être retranscrites, et avec l''arrivée de nouvelles voix de synthèse et de modèles vidéo, il y a 100% de chances que [vos proches] puissent vivre avec vous éternellement après qu''ils aient quitté leur corps physique», écrit l''informaticien. Pratik Desai estime même que cela sera possible d''ici à la fin de l''année. Le but avec ces données récoltées? Créer un avatar à l''effigie de la personne décédée à qui vous voulez parler. L''informaticien de la Silicon Valley n''est pas le premier à avoir développé cette idée. L''entreprise Somnium Space, notamment, compte offrir cette possibilité. «Si je meurs, les gens, par exemple mes enfants, peuvent venir et avoir une conversation avec mon avatar, qui agit avec mes gestes et ma voix», imagine auprès de Vice Artur Sychov, fondateur de l''entreprise. Ce dernier souhaite que cette intelligence artificielle (IA) soit capable de passer le test de Turing –dont l''objectif est, pour un utilisateur humain, de faire la différence entre une conversation générée par un humain ou un ordinateur. «Pendant les dix premières minutes où vous parlerez à cette personne, vous ne saurez pas que c''est une IA. C''est ça le but», décrit le PDG de Somnium Space.', 'https://www.buzzwebzine.fr/wp-content/uploads/2022/09/psy-virtuel-intelligence-artificielle-psychiatre-1-450x253.jpg', 3);
INSERT INTO public.contenus
(id, titre, description, texte, images, idauteur)
VALUES( 'IA : voici le temps des fermes à articles commerciaux... et de désinformation', 'Une étude confirme ce que beaucoup soupçonnaient déjà : les articles rédigés en masse à l''aide de l''intelligence artificielle générative prolifèrent, et le résultat est aussi affligeant que dangereux.', '<p>Si ChatGPT et ses semblables peuvent grandement aider à <a href="https://www.clubic.com/chatgpt/tutoriel-458211-comment-utiliser-chatgpt-pour-vous-aider-dans-votre-travail-de-redaction.html">synthétiser un travail fastidieux qui pourrait prendre des heures</a>, leur utilisation excessive peut poser un réel problème.</p><h2>Des centaines d''articles publiés chaque jour</h2><p>NewsGuard, une organisation qui lutte contre la désinformation, a mené une étude pour identifier les sites produisant de grandes quantités de contenu généré par l''IA. À l''aide de plusieurs outils, ils ont pu mettre en évidence 49 d''entre eux, rédigés dans sept langues différentes, dont le français et l''anglais.</p><p>Véritables fermes à contenus, ils produisent en très grande quantité des articles liés à de nombreux sujets de société, tels que l''environnement, la politique, la santé ou la finance. Selon les chercheurs, «&nbsp;<i>certains publient des centaines d''articles par jour</i>&nbsp;», tous accompagnés de publicités, ce qui rend cette activité lucrative.</p><p>Comme ces intelligences artificielles génératives ont certaines limites, simplement techniques ou décidées par leurs développeurs, des messages d''erreur ou d''avertissement peuvent rapidement apparaître dans le contenu final. Sans compter les nombreux éléments conversationnels propres aux chatbots, qui déjouent la vigilance des éditeurs. C''est grâce à ces messages que les chercheurs ont pu mener leur enquête, en utilisant des mots-clés spécifiques sur les moteurs de recherche.</p>', 'images/0muBaVngXxkespgR2AHMQGqLwb6wP6LFmKismJe8.jpg', 1);
